### ISSUE TITLE
split syntax doesn't seem to work on newer versions of TF

### ISSUE THREAD

**Issue by ilyakazm** [manheim/tf_efs_mount#4]
Hey folks,

Thanks for making this module! Very useful for lazy dudes like me :). 
I was using your module in my configuration, and noticed that TF errors on `count = "${length(split(",", var.subnets))}"` with the following error:

`Error refreshing state: 1 error(s) occurred:`

`* module.efs_logstash.aws_efs_mount_target.logstash: At column 10, line 1: split: argument 2 should be type string, got type list in:`

`${length(split(",", var.subnet_ids))}`

However, if I remove the split part and make it look like `${length(var.subnet_ids)}` all works as expected. I'm wondering if that's only me or it's common to newer versions of TF that may have changed syntax and it's not valid anymore.
I can make a pull request  for this change, but I'd like to confirm it's indeed a thing or it's just me.

Environment:

OS: Ubuntu 17.04
Terraform version: 0.9.8

Thanks!

**Comment by jniesen** [comment]
Most likely not you. This was written back when you couldn't have variables that were lists and maps. Back then you had to turn a comma separated string into a list by using a split. But now, if the variable `var.subnet_ids` is already a list, there's no need to split.

I'll look into fixing this in the morning. Thank you for pointing this out.

**Comment by vikas027** [comment]
Just tested the latest code with terraform v0.9.11. All looks good.

**Comment by jantman** [comment]
Closing per last comment on the issue.
